import React, { useState } from 'react';
import { Icon } from '../Icons';
import { submitWebsite, getTaskStatus } from '../../api';

interface Props {
  taskId: string;
}

export const WebsiteForm: React.FC<Props> = ({ taskId }) => {
  const [step, setStep] = useState<'form' | 'processing' | 'done'>('form');
  const [businessName, setBusinessName] = useState('');
  const [businessType, setBusinessType] = useState('');
  const [description, setDescription] = useState('');
  const [colorScheme, setColorScheme] = useState('');
  const [progress, setProgress] = useState(0);
  const [html, setHtml] = useState('');
  const [error, setError] = useState('');
  const [showPreview, setShowPreview] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStep('processing');
    setError('');

    try {
      await submitWebsite(taskId, { businessName, businessType, description, colorScheme });
      const interval = setInterval(async () => {
        try {
          const status = await getTaskStatus(taskId);
          setProgress(status.progress || 0);
          if (status.status === 'completed') {
            clearInterval(interval);
            setHtml(status.output?.html || '');
            setStep('done');
          } else if (status.status === 'failed') {
            clearInterval(interval);
            setError(status.error || 'Generation failed');
            setStep('form');
          }
        } catch {}
      }, 2000);
    } catch (err: any) {
      setError(err.message);
      setStep('form');
    }
  };

  if (step === 'processing') {
    return (
      <div className="bg-cyber-800 border border-purple-500/30 rounded-lg p-8 text-center">
        <div className="w-16 h-16 mx-auto mb-6 rounded-full bg-purple-500/10 border border-purple-500 flex items-center justify-center animate-pulse shadow-[0_0_30px_rgba(168,85,247,0.2)]">
          <Icon name="Code" className="w-8 h-8 text-purple-400" />
        </div>
        <h3 className="text-xl font-bold text-gray-100 mb-2">FORGE-9 Is Building Your Website</h3>
        <p className="text-gray-400 text-sm mb-6">Production Division agents are crafting a stunning, responsive website...</p>
        <div className="w-full bg-cyber-900 h-3 rounded-full overflow-hidden mb-3">
          <div className="bg-gradient-to-r from-purple-500 to-cyber-accent h-full rounded-full transition-all duration-500" style={{ width: `${progress}%` }} />
        </div>
        <p className="text-xs font-mono text-gray-500">{progress}% — Generating HTML, styling, animations...</p>
      </div>
    );
  }

  if (step === 'done') {
    return (
      <div className="space-y-6">
        <div className="bg-cyber-success/10 border border-cyber-success/30 rounded-lg p-4 flex items-center gap-3">
          <Icon name="CheckCircle" className="w-5 h-5 text-cyber-success" />
          <span className="text-cyber-success font-medium">Website Generated by FORGE-9 (Production Division)</span>
        </div>

        <div className="flex gap-3">
          <button onClick={() => setShowPreview(!showPreview)}
            className="bg-cyber-accent/10 text-cyber-accent border border-cyber-accent/50 px-4 py-2 rounded flex items-center gap-2 hover:bg-cyber-accent/20 transition-colors">
            <Icon name="Eye" className="w-4 h-4" /> {showPreview ? 'Hide' : 'Show'} Preview
          </button>
          <button
            onClick={() => {
              const blob = new Blob([html], { type: 'text/html' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url; a.download = `${businessName || 'website'}.html`;
              a.click(); URL.revokeObjectURL(url);
            }}
            className="bg-purple-500/10 text-purple-400 border border-purple-500/50 px-4 py-2 rounded flex items-center gap-2 hover:bg-purple-500/20 transition-colors">
            <Icon name="Download" className="w-4 h-4" /> Download HTML
          </button>
          <button
            onClick={() => {
              const win = window.open('', '_blank');
              if (win) { win.document.write(html); win.document.close(); }
            }}
            className="bg-cyber-800 text-gray-300 border border-cyber-700 px-4 py-2 rounded flex items-center gap-2 hover:bg-cyber-700 transition-colors">
            <Icon name="ExternalLink" className="w-4 h-4" /> Open in New Tab
          </button>
        </div>

        {showPreview && (
          <div className="border border-cyber-700 rounded-lg overflow-hidden bg-white">
            <iframe srcDoc={html} className="w-full h-[600px] border-0" title="Website Preview" sandbox="allow-scripts" />
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="bg-cyber-800 border border-cyber-700 rounded-lg p-6">
      <div className="mb-6">
        <h3 className="text-xl font-bold text-gray-100 flex items-center gap-2">
          <Icon name="Code" className="w-6 h-6 text-purple-400" />
          Website Forge — Production Division
        </h3>
        <p className="text-gray-400 text-sm mt-1">CTO FORGE-9 will generate a complete, production-quality landing page for your business.</p>
      </div>

      {error && (
        <div className="bg-cyber-warning/10 border border-cyber-warning text-cyber-warning text-sm p-3 rounded mb-4 flex items-center gap-2">
          <Icon name="AlertTriangle" className="w-4 h-4" /> {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-300 mb-1">Business Name *</label>
          <input type="text" required value={businessName} onChange={(e) => setBusinessName(e.target.value)}
            className="w-full bg-cyber-900 border border-cyber-700 rounded px-4 py-3 text-gray-100 focus:outline-none focus:border-purple-500 transition-all"
            placeholder="e.g., NexaTech Solutions" />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-300 mb-1">Industry / Type</label>
          <input type="text" value={businessType} onChange={(e) => setBusinessType(e.target.value)}
            className="w-full bg-cyber-900 border border-cyber-700 rounded px-4 py-3 text-gray-100 focus:outline-none focus:border-purple-500 transition-all"
            placeholder="e.g., AI SaaS, E-commerce, Fitness Studio" />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-300 mb-1">Description</label>
          <textarea rows={3} value={description} onChange={(e) => setDescription(e.target.value)}
            className="w-full bg-cyber-900 border border-cyber-700 rounded px-4 py-3 text-gray-100 focus:outline-none focus:border-purple-500 transition-all resize-none"
            placeholder="What does your business do? Key selling points?" />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-300 mb-1">Color Scheme Preference</label>
          <input type="text" value={colorScheme} onChange={(e) => setColorScheme(e.target.value)}
            className="w-full bg-cyber-900 border border-cyber-700 rounded px-4 py-3 text-gray-100 focus:outline-none focus:border-purple-500 transition-all"
            placeholder="e.g., Dark theme with blue accents, or Clean white with green" />
        </div>
        <button type="submit"
          className="w-full bg-purple-500 text-white font-bold py-3 rounded hover:bg-purple-600 transition-colors flex items-center justify-center gap-2 shadow-[0_0_15px_rgba(168,85,247,0.3)]">
          <Icon name="Zap" className="w-5 h-5" /> Activate Production Agent
        </button>
      </form>
    </div>
  );
};
